"""cretae data

Revision ID: 48768c1d51ed
Revises: 
Create Date: 2021-11-03 14:19:03.325901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48768c1d51ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obat', sa.Column('kondisi', sa.String(length=80), nullable=True))
    op.alter_column('pendaftaran', 'status',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pendaftaran', 'status',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.drop_column('obat', 'kondisi')
    # ### end Alembic commands ###
